import { Link } from 'react-router-dom'
import { useLang } from '../lib/LanguageContext'

export default function DisclaimerPage() {
  const { lang } = useLang()

  const sections = {
    en: [
      {
        number: '01',
        icon: '⚖️',
        title: 'AI-Generated Analysis',
        critical: true,
        body: `EverAI provides automated, AI-generated analysis based on publicly available information retrieved at the time of analysis. Results may contain inaccuracies, omissions, or errors. This tool is for informational and educational purposes only and must not be considered a final, definitive, or authoritative fact-checking verdict.`,
      },
      {
        number: '02',
        icon: '📊',
        title: 'Probabilistic Scores',
        body: `All credibility scores, confidence percentages, and verdicts (True / False / Partially True / Insufficient Evidence) are probabilistic outputs generated by machine learning models. They represent statistical likelihood, not absolute truth. A score of 90/100 does not guarantee accuracy. A score of 20/100 does not guarantee falsehood.`,
      },
      {
        number: '03',
        icon: '🚫',
        title: 'No Publisher Affiliation',
        body: `EverAI has no affiliation, partnership, endorsement, or business relationship with any publisher, news organisation, journalist, media house, political party, government body, or any entity mentioned in analysis results. Publisher credibility scores are model-generated assessments and do not represent official ratings.`,
      },
      {
        number: '04',
        icon: '🔍',
        title: 'Evidence Limitations',
        body: `Evidence gathered by EverAI is limited to publicly accessible web sources available at the time of the query. The system may miss recent publications, paywalled content, regional sources, or information in languages other than English. Absence of supporting evidence does not prove a claim is false.`,
      },
      {
        number: '05',
        icon: '👤',
        title: 'No Legal or Defamatory Intent',
        body: `EverAI analysis results are not legal opinions and carry no legal weight. Results should not be used to defame, harass, or harm any individual, organisation, or entity. Users who publish or share EverAI results as definitive proof of misinformation do so at their own legal risk. We disclaim all liability for misuse.`,
      },
      {
        number: '06',
        icon: '🔄',
        title: 'Information Currency',
        body: `The internet changes rapidly. A claim verified as true today may become outdated tomorrow. EverAI does not guarantee that its analysis reflects the most current state of any given fact. Always cross-reference with multiple trusted sources before drawing conclusions.`,
      },
      {
        number: '07',
        icon: '🛡️',
        title: 'Limitation of Liability',
        body: `EverAI, its creators, and contributors shall not be held liable for any direct, indirect, incidental, consequential, or punitive damages arising from reliance on analysis results. This includes but is not limited to: reputational damage, financial loss, legal consequences, or harm caused by acting on incorrect verdicts.`,
      },
      {
        number: '08',
        icon: '📱',
        title: 'WhatsApp & Third-Party Use',
        body: `EverAI's WhatsApp integration is provided via Twilio's sandbox environment. Messages sent to the bot are processed by OpenAI's GPT-4o model and Tavily search. By using the WhatsApp bot, you consent to your query text being processed by these third-party services. Do not send sensitive, private, or confidential information.`,
      },
      {
        number: '09',
        icon: '🧠',
        title: 'Human Judgment Required',
        body: `EverAI is a decision-support tool, not a decision-making tool. The final judgment on whether any piece of information is true or false must always rest with an informed human being. Do not use EverAI results as the sole basis for important decisions, publications, legal actions, or public statements.`,
      },
      {
        number: '10',
        icon: '📋',
        title: 'Data & Privacy',
        body: `Queries submitted to EverAI are stored in our database for the purpose of improving the system and tracking analysis history. Query text, analysis results, and anonymous usage patterns may be reviewed by the development team. We do not sell or share your data with third parties for marketing purposes.`,
      },
    ],
    hi: [
      {
        number: '01', icon: '⚖️', title: 'AI-जनित विश्लेषण', critical: true,
        body: 'EverAI सार्वजनिक रूप से उपलब्ध जानकारी के आधार पर स्वचालित, AI-जनित विश्लेषण प्रदान करता है। परिणामों में अशुद्धियां, चूक या त्रुटियां हो सकती हैं। यह उपकरण केवल सूचनात्मक उद्देश्यों के लिए है और इसे अंतिम, निश्चित या आधिकारिक तथ्य-जांच का निर्णय नहीं माना जाना चाहिए।',
      },
      {
        number: '02', icon: '📊', title: 'संभाव्यतावादी स्कोर',
        body: 'सभी विश्वसनीयता स्कोर, विश्वास प्रतिशत और निर्णय मशीन लर्निंग मॉडल द्वारा उत्पन्न संभाव्यतावादी आउटपुट हैं। वे सांख्यिकीय संभावना का प्रतिनिधित्व करते हैं, निरपेक्ष सत्य का नहीं।',
      },
      {
        number: '03', icon: '🚫', title: 'कोई प्रकाशक संबद्धता नहीं',
        body: 'EverAI का किसी भी प्रकाशक, समाचार संगठन, पत्रकार, राजनीतिक दल, सरकारी निकाय या विश्लेषण परिणामों में उल्लिखित किसी भी इकाई के साथ कोई संबद्धता, साझेदारी या व्यावसायिक संबंध नहीं है।',
      },
      {
        number: '04', icon: '⚖️', title: 'दायित्व की सीमा',
        body: 'EverAI और इसके निर्माता विश्लेषण परिणामों पर निर्भरता से उत्पन्न किसी भी प्रत्यक्ष, अप्रत्यक्ष, आकस्मिक या परिणामी क्षति के लिए उत्तरदायी नहीं होंगे।',
      },
    ],
    mr: [
      {
        number: '01', icon: '⚖️', title: 'AI-निर्मित विश्लेषण', critical: true,
        body: 'EverAI सार्वजनिकरित्या उपलब्ध माहितीवर आधारित स्वयंचलित, AI-निर्मित विश्लेषण प्रदान करते. परिणामांमध्ये अचूकता, वगळणे किंवा त्रुटी असू शकतात. हे साधन केवळ माहितीपर उद्देशांसाठी आहे.',
      },
      {
        number: '02', icon: '📊', title: 'संभाव्यता-आधारित गुण',
        body: 'सर्व विश्वासार्हता गुण, आत्मविश्वास टक्केवारी आणि निर्णय हे मशीन लर्निंग मॉडेलद्वारे तयार केलेले संभाव्य आउटपुट आहेत. ते परिपूर्ण सत्य दर्शवत नाहीत.',
      },
      {
        number: '03', icon: '🚫', title: 'कोणताही प्रकाशक संबंध नाही',
        body: 'EverAI चा कोणत्याही प्रकाशक, वृत्त संस्था, पत्रकार, राजकीय पक्ष, सरकारी संस्था किंवा विश्लेषण निकालांमध्ये नमूद केलेल्या कोणत्याही संस्थेशी कोणताही संबंध नाही.',
      },
      {
        number: '04', icon: '⚖️', title: 'दायित्वाची मर्यादा',
        body: 'EverAI आणि त्याचे निर्माते विश्लेषण परिणामांवर अवलंबून राहिल्यामुळे होणाऱ्या कोणत्याही प्रत्यक्ष, अप्रत्यक्ष किंवा परिणामी नुकसानासाठी जबाबदार नाहीत.',
      },
    ],
  }

  const content = sections[lang] || sections.en

  return (
    <div style={{ minHeight: '100vh', background: 'var(--paper)' }}>

      {/* ── HERO ── */}
      <div style={{
        background: 'var(--ink)', color: 'var(--paper)',
        borderBottom: '4px solid var(--ink)',
        padding: '3rem 1.5rem 2.5rem',
      }}>
        <div style={{ maxWidth: 860, margin: '0 auto' }}>

          {/* Top label */}
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: '.65rem',
            letterSpacing: '.18em', color: '#888', marginBottom: '1rem',
            textTransform: 'uppercase',
          }}>
            Legal · {lang === 'hi' ? 'कानूनी' : lang === 'mr' ? 'कायदेशीर' : 'Terms of Use'}
          </div>

          {/* Big headline */}
          <h1 style={{
            fontFamily: 'var(--font-display)',
            fontSize: 'clamp(2.5rem, 8vw, 6rem)',
            lineHeight: .95, letterSpacing: '.02em',
            marginBottom: '1.2rem',
          }}>
            DISCLAIMER
            <br />
            <span style={{ color: '#f87171' }}>&amp; TERMS</span>
          </h1>

          {/* Intro paragraph */}
          <p style={{
            fontSize: 'clamp(.9rem, 2vw, 1.05rem)',
            color: '#ccc', lineHeight: 1.7, maxWidth: 620,
            marginBottom: '1.8rem',
          }}>
            {lang === 'hi'
              ? 'EverAI एक AI-संचालित उपकरण है। इसे अंतिम सत्य नहीं माना जाना चाहिए। उपयोग से पहले कृपया इन महत्वपूर्ण शर्तों को पढ़ें।'
              : lang === 'mr'
              ? 'EverAI एक AI-चालित साधन आहे. हे अंतिम सत्य मानले जाऊ नये. वापरण्यापूर्वी कृपया या महत्त्वाच्या अटी वाचा.'
              : 'EverAI is an AI-powered tool. It is not a substitute for professional fact-checkers, journalists, or legal advisors. Please read these terms carefully before using this service.'
            }
          </p>

          {/* Warning strip */}
          <div style={{
            border: '2px solid #f87171', padding: '.9rem 1.2rem',
            display: 'flex', gap: '.8rem', alignItems: 'flex-start',
            background: 'rgba(248,113,113,.08)',
          }}>
            <span style={{ fontSize: '1.3rem', lineHeight: 1, flexShrink: 0 }}>⚠️</span>
            <p style={{ fontSize: '.88rem', color: '#fca5a5', lineHeight: 1.6, margin: 0 }}>
              <strong style={{ color: '#f87171', fontFamily: 'var(--font-display)', letterSpacing: '.05em' }}>
                IMPORTANT:{' '}
              </strong>
              {lang === 'hi'
                ? 'EverAI द्वारा दिए गए निर्णय अंतिम नहीं हैं। AI गलत हो सकता है। सभी परिणाम संभाव्य हैं और मानवीय सत्यापन आवश्यक है।'
                : lang === 'mr'
                ? 'EverAI द्वारे दिलेले निर्णय अंतिम नाहीत. AI चुकीचे असू शकते. सर्व परिणाम संभाव्य आहेत आणि मानवी पडताळणी आवश्यक आहे.'
                : 'Verdicts issued by EverAI are NOT final. AI can be wrong. All results are probabilistic and human verification is always required before taking any action based on this tool.'
              }
            </p>
          </div>
        </div>
      </div>

      {/* ── Key stats bar ── */}
      <div style={{
        borderBottom: '3px double var(--ink)',
        background: 'var(--paper-dark)',
        padding: '.8rem 1.5rem',
      }}>
        <div style={{
          maxWidth: 860, margin: '0 auto',
          display: 'flex', gap: '2rem', flexWrap: 'wrap',
          fontFamily: 'var(--font-mono)', fontSize: '.72rem',
          color: 'var(--grey)', letterSpacing: '.08em',
        }}>
          {[
            ['VERSION', 'v2.0'],
            ['LAST UPDATED', 'March 2025'],
            ['JURISDICTION', 'India'],
            ['LANGUAGE', 'EN / HI / MR'],
          ].map(([k, v]) => (
            <div key={k}>
              <span style={{ color: 'var(--ink)', fontWeight: 600 }}>{k}:</span> {v}
            </div>
          ))}
        </div>
      </div>

      {/* ── Main content ── */}
      <div style={{ maxWidth: 860, margin: '0 auto', padding: '2rem 1.5rem' }}>

        {content.map((sec, i) => (
          <div
            key={sec.number}
            className="fade-up"
            style={{
              marginBottom: '1.5rem',
              borderLeft: `4px solid ${sec.critical ? '#f87171' : 'var(--ink)'}`,
              paddingLeft: '1.2rem',
            }}
          >
            <div style={{ display: 'flex', gap: '.8rem', alignItems: 'baseline', flexWrap: 'wrap', marginBottom: '.5rem' }}>
              <span style={{
                fontFamily: 'var(--font-display)',
                fontSize: '2.5rem', lineHeight: 1,
                color: sec.critical ? '#f87171' : 'var(--paper-dark)',
              }}>{sec.number}</span>
              <div>
                <span style={{ fontSize: '1.2rem', marginRight: '.4rem' }}>{sec.icon}</span>
                <span style={{
                  fontFamily: 'var(--font-display)',
                  fontSize: 'clamp(1.1rem, 3vw, 1.5rem)',
                  letterSpacing: '.04em',
                  color: sec.critical ? '#c41a1a' : 'var(--ink)',
                }}>{sec.title}</span>
                {sec.critical && (
                  <span style={{
                    marginLeft: '.6rem',
                    fontFamily: 'var(--font-mono)', fontSize: '.65rem',
                    padding: '.1rem .4rem',
                    background: '#f87171', color: 'white',
                    letterSpacing: '.08em', textTransform: 'uppercase',
                  }}>CRITICAL</span>
                )}
              </div>
            </div>
            <p style={{
              fontSize: '.92rem', lineHeight: 1.75,
              color: '#333', maxWidth: 700,
            }}>{sec.body}</p>
          </div>
        ))}

        {/* ── Acceptance box ── */}
        <div className="card" style={{
          marginTop: '2.5rem', padding: '1.5rem',
          borderColor: 'var(--ink)', background: 'var(--paper-dark)',
        }}>
          <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '1.4rem', marginBottom: '.7rem' }}>
            ✅ BY USING EVERAI, YOU AGREE:
          </h3>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '.5rem' }}>
            {[
              'Results are AI-generated and may be inaccurate',
              'Scores are probabilistic, not absolute truth',
              'EverAI is not affiliated with any publisher',
              'You will not use results to defame anyone',
              'You will cross-reference important claims independently',
              'EverAI is not liable for decisions you make',
              'Your query text is stored for analysis purposes',
              'Human judgment always overrides AI output',
            ].map((item, i) => (
              <div key={i} style={{
                display: 'flex', gap: '.5rem', alignItems: 'flex-start',
                fontFamily: 'var(--font-mono)', fontSize: '.75rem',
                color: 'var(--grey)', lineHeight: 1.5,
              }}>
                <span style={{ color: 'var(--green)', flexShrink: 0 }}>✓</span>
                {item}
              </div>
            ))}
          </div>
        </div>

        {/* ── Contact ── */}
        <div style={{
          marginTop: '1.5rem', padding: '1rem 1.2rem',
          border: '1px solid var(--border-light)',
          fontFamily: 'var(--font-mono)', fontSize: '.75rem', color: 'var(--grey)',
          lineHeight: 1.8,
        }}>
          <strong style={{ color: 'var(--ink)' }}>CONTACT / DISPUTES:</strong><br />
          If you believe an analysis result is incorrect or harmful, please submit feedback via our{' '}
          <Link to="/feedback" style={{ color: 'var(--blue)' }}>Feedback page</Link>.
          We review all reports and may correct or remove erroneous results.
          EverAI is operated as an independent AI research project. Grievances may be raised at{' '}
          <span style={{ color: 'var(--ink)', fontWeight: 600 }}>ever-ai-six.vercel.app/feedback</span>.
        </div>

        {/* ── Footer actions ── */}
        <div style={{
          display: 'flex', gap: '1rem', marginTop: '2rem',
          flexWrap: 'wrap', alignItems: 'center',
          borderTop: '2px solid var(--ink)', paddingTop: '1.5rem',
        }}>
          <Link to="/" className="btn">Start Analyzing →</Link>
          <Link to="/feedback" className="btn btn-ghost">Submit Feedback</Link>
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: '.68rem', color: 'var(--grey)', marginLeft: 'auto' }}>
            © EverAI {new Date().getFullYear()} · For informational use only
          </span>
        </div>
      </div>
    </div>
  )
}
